(require 'soundklaus-utils)
(require 'ert)

(ert-deftest soundklaus-url-encode-test ()
  (should (equal (soundklaus-url-encode "") ""))
  (should (equal (soundklaus-url-encode "x") "x"))
  (should (equal (soundklaus-url-encode "=") "%3D"))
  (should (equal (soundklaus-url-encode "a 1") "a%201"))
  (should (equal (soundklaus-url-encode '(a-1 1)) "a-1=1"))
  (should (equal (soundklaus-url-encode '((a 1) (b nil))) "a=1"))
  (should (equal (soundklaus-url-encode '((a . 1) (b . nil))) "a=1"))
  (should (equal (soundklaus-url-encode '((a-1 1) (b-2 2))) "a-1=1&b-2=2"))
  (should (equal (soundklaus-url-encode '((a-1 . 1) (b-2 . 2))) "a-1=1&b-2=2")))

(ert-deftest soundklaus-dasherize-test ()
  (should (equal "" (soundklaus-dasherize "")))
  (should (equal "-" (soundklaus-dasherize "-")))
  (should (equal "-" (soundklaus-dasherize "_")))
  (should (equal "client-id" (soundklaus-dasherize "client_id")))
  (should (equal 'client-id (soundklaus-dasherize 'client_id)))
  (should (equal :client-id (soundklaus-dasherize :client_id)))
  (should (equal '(client-id . "client_id") (soundklaus-dasherize '(client_id . "client_id"))))
  (should (equal (soundklaus-dasherize '((client_id . "client_id") ("client_secret" "client_secret")))
                 '((client-id . "client_id") ("client-secret" "client_secret"))))
  (let ((hash (make-hash-table)))
    (puthash "client_id" "client-id" hash)
    (puthash 'client_secret "client-secret" hash)
    (puthash :grant_type "grant-type" hash)
    (let ((hash (soundklaus-dasherize hash)))
      (should (equal 3 (hash-table-count hash)))
      (should (equal "client-id" (gethash "client-id" hash)))
      (should (equal "client-secret" (gethash 'client-secret hash)))
      (should (equal "grant-type" (gethash :grant-type hash))))))

(ert-deftest soundklaus-underscore-test ()
  (should (equal "" (soundklaus-underscore "")))
  (should (equal "_" (soundklaus-underscore "_")))
  (should (equal "_" (soundklaus-underscore "-")))
  (should (equal "client_id" (soundklaus-underscore "client-id")))
  (should (equal 'client_id (soundklaus-underscore 'client-id)))
  (should (equal :client_id (soundklaus-underscore :client-id)))
  (should (equal '(client_id . "client-id") (soundklaus-underscore '(client-id . "client-id"))))
  (should (equal (soundklaus-underscore '((client-id . "client_id") ("client-secret" "client_secret")))
                 '((client_id . "client_id") ("client_secret" "client_secret"))))
  (let ((hash (make-hash-table)))
    (puthash "client-id" "client-id" hash)
    (puthash 'client-secret "client-secret" hash)
    (puthash :grant-type "grant-type" hash)
    (let ((hash (soundklaus-underscore hash)))
      (should (equal 3 (hash-table-count hash)))
      (should (equal "client-id" (gethash "client_id" hash)))
      (should (equal "client-secret" (gethash 'client_secret hash)))
      (should (equal "grant-type" (gethash :grant_type hash))))))
